public class Appartment 
{
    public static void addTwoNumber(Integer firstNumber, Integer secNumber)
    {
        Integer Sum;
        Sum = firstNumber + secNumber;
        System.debug('-----' + Sum);
        
    }
    public static void howToUseStringVariable()
    {String AllCourses;
     String firstCourse;
     String secCourse;
     firstCourse='Java';
     secCourse='Apex';
     AllCourses = firstCourse + secCourse;
     System.debug('-------firstCourse' + firstCourse);
     System.debug('-------secCourse' + secCourse);
     System.debug('-------AllCourses' + AllCourses);
        
    }
}