public class Input_example {
    
    public string lastName {set;get;}
    public string firstName {set;get;}
    public string city {set;get;}
    public string pancard {set;get;}
    public string address1 {set;get;}
    public string address2 {set;get;}
    public string[] course {set;get;}
    public string gender {set;get;}
    public Input_example(){
        
        course=new string[4];
            }
}