public class SOQLDemo {
    /*
   
 Account insertedAccount = [SELECT Name, Id FROM Account];
    
    insertedAccount.Active_CheckBox__c = 'insertedAccount';
    try {
        update insertedAccount;
    }catch (Exception e)
        
    
*/
}



/* //Account objAcc;
    
   // List<Account> lstAccounts = new List<Account>();
    
    //public void fetchAllAcc()
    
  //  {
    //    lstAccounts = [SELECT Name, Id FROM Account ];
        */